version: 0.0
os: ubuntu
files:
 - source: /
   destination: /home/ec2-user/aws-codedeploy
 - source: requirements.txt
   destination: /home/ec2-user/aws-codedeploy
permissions:
  - object: /home/ec2-user/aws-codedeploy/app.py
    owner: ec2-user
    mode: 644
    type:
      - file
 
  - object: /home/ec2-user/aws-codedeploy/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
