version: '3.3'

services:
  pythonapp:
    container_name: pythonapp
    image: 921079650/eapr.group.c
    build: .
    environment:
      - JWT_SECRET_KEY=qazwsxedc&mac
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eapr
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
